name: colorenv
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - contourpy=1.2.1
  - cycler=0.11.0
  - eigen=3.4.0
  - expat=2.6.4
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - icc_rt=2022.1.0
  - icu=73.1
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libglib=2.78.4
  - libiconv=1.16
  - libogg=1.3.5
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numexpr=2.10.1
  - numpy=2.0.2
  - numpy-base=2.0.2
  - opencv=4.10.0
  - openjpeg=2.5.2
  - openssl=3.0.16
  - packaging=24.2
  - pandas=2.2.3
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.40.0
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tomli=2.0.1
  - tornado=6.4.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - av==14.2.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - idna==3.10
      - pymsteams==0.2.5
      - requests==2.32.3
      - urllib3==2.3.0
